apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter-worker0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter-worker0
  template:
    metadata:
      labels:
        app: node-exporter-worker0
    spec:
      nodeSelector:
        node-type: worker-0
      containers:
        - name: node-exporter-worker0
          image: bitnami/node-exporter:1.6.1 # Update to the desired version
          ports:
            - name: metrics
              containerPort: 9100