apiVersion: v1
kind: Service
metadata:
  name: worker-0-metrics
spec:
  selector:
    app: node-exporter-worker0
  ports:
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: metrics