apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['master-metrics:9100', 'monitor-metrics:9100', 'worker-0-metrics:9100'] # Use the service name
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics-service:8080'] # Use the service name