apiVersion: v1
kind: Service
metadata:
  name: master-metrics
spec:
  selector:
    app: node-exporter-master
  ports:
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: metrics